# Generated by Django 2.2.7 on 2019-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
