# Generated by Django 2.2.7 on 2019-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_contact_temperatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='umidita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
