# Generated by Django 2.2.7 on 2019-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_contact_unita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unita',
            field=models.CharField(choices=[('gradi centigradi', 'gradi centigradi'), ('gradi farenight', 'gradi fahrenheit')], max_length=200),
        ),
    ]
