# Generated by Django 2.2.7 on 2019-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_auto_20191213_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unita',
            field=models.CharField(choices=[('gradi centigradi', 'gradi centigradi'), ('gradi fahrenheit', 'gradi fahrenheit')], default='gradi centigradi', max_length=200),
        ),
    ]
